# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vaswebgit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://vasregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_06f48dc136894dcdbaa430ea6e852c9c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_07829bbd1ba64891b69c190f35cd9b9f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vasregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_06f48dc136894dcdbaa430ea6e852c9c }}/hello-express:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vaswebgit'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_95c5be1880b74b12b9109b12f26d2901 }}
        images: 'vasregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_06f48dc136894dcdbaa430ea6e852c9c }}/hello-express:${{ github.sha }}'